config/routes.rb
Whatsay::Application.routes.draw do

  devise_for :users,:path_names => {:sign_in => "login", :sign_out => "logout"} , :controllers => {:registrations => "registrations", :confirmations => "confirmations"} do
    get '/logout', :to => "devise/sessions#destroy", :as => :destroy_user_session
    get '/login', :to => "pages#index", :as => :new_user_session
    get '/sign_up' => 'devise/registrations#new', :as => :new_user_registration
    post'/sign_up' => 'devise/registrations#create', :as => :user_registration
  end

  resources :polls

  root to: 'pages#index'

end

app/models/answer.rb
class Answer
  include Mongoid::Document
  include Mongoid::Timestamps

  #associations
  embedded_in :poll
  #attr_accessible
  attr_accessible :choice, :user_id

  #fields
  field :choice,    :type => Array, :default=>[]
  field :user_id,   :type => BSON::ObjectId

  #callbacks
  after_create :update_answers_count

  def update_answers_count
    #write_attribute(:answers_count, self.answers.size) 
    Poll.collection.update( {'_id' => self._parent._id}, 
                              {'$inc' => {'answers_count' => 1}},{:updated_at=>Time.now.utc} )
  end


end

app/models/poll.rb
class Poll
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Rateable
  RATING_RANGE = (1..5)

  #associations
  belongs_to :user
  #has_one :suggestion_poll, :dependent => :destroy
  #has_one :vote_poll, :dependent => :destroy
  embeds_many :suggestion_field
  embeds_many :answers

  #attr_accessible

  attr_accessible :topic,:description,:type, :field_options,:answers_count,:updated_at, :multiple_ans

  #fields
  field :topic,          :type => String
  field :description,    :type => String
  field :type,           :type => String
  field :field_options,  :type=> Array,    :default=> []
  field :multiple_ans,   :type => Boolean,:default=>false
  field :answers_count,   :type => Integer,:default=>0 

  #options => array [{option_value => "Yes", votes: "0"}, {}, {}]

  #validations
  validates :topic, :presence => true


  scope :answered_by, ->(user,poll) { where("answers.user_id" => user.id,:_id=>poll.id) }

  #callbacks
  #after_update :save_count

  def self.get_by_id(id)
    Poll.where(:_id=>id).first
  end

  def user_mark(rater)
    r = self.rating_marks.where(:rater_id => rater.id, :rater_class => rater.class.to_s).first
    r ? r.mark : nil
  end

  def self.top_polls
    Poll.all.sort_by{|poll| poll.answers_count}
  end

  def self.latest_polls
    Poll.all.sort_by{|poll| poll.updated_at.to_i}
  end

  def answered_by?(user)
    Poll.where("answers.user_id" => user.id).to_a.size >= 1
  end
  # def save_count
  #   write_attribute(:answers_count, self.answers.size) 
  # end
end

app/models/suggestion_field.rb
class SuggestionField
  include Mongoid::Document
  include Mongoid::Timestamps

  #associations
  embedded_in :poll
  #attr_accessible
  attr_accessible :fields

  #fields
  field :fields,    :type => Hash,:default=>{}
  field :user_id,   :type => BSON::ObjectId  

    #callbacks
  after_create :update_answers_count

  def update_answers_count
    #write_attribute(:answers_count, self.answers.size) 
    Poll.collection.update( {'_id' => self._parent._id}, 
                              {'$inc' => {'answers_count' => 1}},{:updated_at=>Time.now.utc} )
  end
end

app/models/suggestion_poll.rb
class SuggestionPoll
  include Mongoid::Document
  include Mongoid::Timestamps

  #associations
  #belongs_to :poll 
  #embeds_many :suggestion_field
  #attr_accessible
  attr_accessible :field_options


  #field :field_options,    :type=> Array,    :default=> []
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  #associations
  has_many :polls

  #attr
  attr_accessible :password,:password_confirmation,:first_name,:last_name,:email

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  field :first_name, :type => String
  field :last_name, :type => String

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_presence_of :password
  validates_presence_of :password_confirmation
end

app/models/vote_poll.rb
class VotePoll
  include Mongoid::Document
  include Mongoid::Timestamps

  #associations
  #belongs_to :poll 
  #embeds_many :answers
  #attr_accessible
  #attr_accessible :multiple_ans, :field_options

  #fields
  #field :multiple_ans,    :type => Boolean,:default=>false
  #field :field_options,    :type=> Array,    :default=> []
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

  def print_logger_info parameter
    logger.info "######{" Controller : "+params[:controller]+" "}#################{" Action : "+params[:action]+" "}###########{" Parameters : "+parameter.inspect+" "}#############}" if Rails.env.development?    
  end

  def after_sign_in_path_for(resource)
    polls_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :send_signed_in_user_to_polls, only: [:index]
  skip_before_filter :authenticate_user!

  def index
  end

  def after_login
  end

  def ask_poll
  end  
  
  def the_poll
  end  
    
  def suggestions
  end  

  private
  def send_signed_in_user_to_polls
    redirect_to :polls if user_signed_in?
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @my_polls = current_user.polls
    @top_polls = Poll.top_polls
    @latest_polls = Poll.latest_polls
  end

  def new
    @poll = current_user.polls.new #TODO use current_user
    #@vote_poll = @poll.build_vote_poll
    #@suggestion_poll = @poll.build_suggestion_poll
  end

  def create
    logger.info ".........>>#{params.inspect}"
    poll = current_user.polls.create({
      :topic         => params[:poll][:topic],
      :description   => params[:poll][:description],
      :type          => params[:poll][:type],
      :multiple_ans  => params[:poll][:multiple_ans],
      :field_options => params[:poll][:field_options].values
      })
  rescue => e
    logger.error "Error: #{e.message} \n #{e.backtrace.join('\n')}"
    render :new
  else
    # success
    redirect_to poll_path(poll)
  end

  def show
    @poll = Poll.find(params[:id])
  end

  def update
    print_logger_info "#{params} #{params[:answers].class}"
    @poll = Poll.get_by_id(params[:id])
    params[:answers].is_a?(String) ? answers = [params[:answers]]  : answers = params[:answers].reject!{|key,value| value=="0"}.values
    @poll.answers.create(:choice => answers, user_id: current_user.id)
    redirect_to :polls, :notice => "Your vote is submitted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource_class
    User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/polls_helper.rb
module PollsHelper
  # def get_poll_options poll
  #   #option_type = poll.multiple_ans ? "check_box" : "radio_button"
  #   #content_tag(:input, :type => :hidden, :id=>"car_input_engine_id", :name=>"car[input_engine_id]", :value=>car_engine_id)
  # end
end

app/views/layouts/application.html.haml
!!!
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/ [if (gte IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Whatsay? :: Online Poll App"
    = stylesheet_link_tag "application", "foundation", "style"
    = javascript_include_tag "vendor/custom.modernizr", "jquery"
    = csrf_meta_tags
  %body
    %header
      .row
        %large-12.columns
          %a{:href => "/"}
            = image_tag("logoOLD.png")
    .row
      %large-12.columns
      - flash.each do |name, msg|
        %div{"data-alert" => "true", :class => "alert-box #{name == :notice ? "success" : "alert"}",:id => "notice_box"}
          %a.close{:href => "#"} &times;
          = msg if msg.is_a?(String)
      = yield
    = javascript_include_tag "application"
    = javascript_include_tag "frontend"

app/views/pages/after_login.html.haml
.row
  .box.large-10.large-offset-1
    %ul.tabs.switchForm
      %li.large-4.columns.selected
        %a{:href => ""} My Polls
      %li.large-4.columns
        %a{:href => ""} Top Polls
      %li.large-4.columns
        %a{:href => ""} Current Polls
    .topPolls.tabDetails#tabCont_1
      %h5 My Polls
      %ul
        %li
          %span.pollQuestion Top Polling Question
          %strong Yes
          %strong No
          %em 80%
          %ul.stars
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
        %li
          %span.pollQuestion
            %a{:href => ""} Top Polling Suggestion
          %strong 70
          %ul.stars
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
        %li
          %span.pollQuestion Top Polling Question
          %strong Yes
          %strong No
          %em 60%
          %ul.stars
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
        %li
          %span.pollQuestion
            %a{:href => ""} Top Polling Suggestion
          %strong 70
          %ul.stars
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
    .topPolls.tabDetails#tabCont_2
      %h5 top polls
      %ul
        %li
          %span.pollQuestion Top Polling Question
          %strong Yes
          %strong No
          %em 80%
          %ul.stars
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
        %li
          %span.pollQuestion
            %a{:href => ""} Top Polling Suggestion
          %strong 70
          %ul.stars
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
        %li
          %span.pollQuestion Top Polling Question
          %strong Yes
          %strong No
          %em 60%
          %ul.stars
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
        %li
          %span.pollQuestion
            %a{:href => ""} Top Polling Suggestion
          %strong 70
          %ul.stars
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
    .currentPolls.tabDetails#tabCont_3
      %h5 Current polls
      %ul
        %li
          %span.pollQuestion Top Polling Question
          %strong Yes
          %strong No
          %em 80%
          %ul.stars
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
        %li
          %span.pollQuestion
            %a{:href => ""} Top Polling Suggestion
          %strong 70
          %ul.stars
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
        %li
          %span.pollQuestion Top Polling Question
          %strong Yes
          %strong No
          %em 60%
          %ul.stars
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
        %li
          %span.pollQuestion
            %a{:href => ""} Top Polling Suggestion
          %strong 70
          %ul.stars
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 
            %li
              %a{:href => "#"} 

app/views/pages/ask_poll.html.haml
.row 
  .large-8.large-offset-2
    %ul.no-bullet.switchForm.tabs 
      %li.large-6 
        %a{:href => "#"} Ask for Votes
      %li.large-6 
        %a{:href => "#"} Ask for Suggestions
.row        
  .large-8.large-offset-2
    %form.custom.askForVotes#tabCont_1.tabDetails{:action => ""}
      %input{:type => "text", :placeholder=>"Topic"}
      %textarea{:name => "", :cols => "30", :rows => "10", :placeholder => "Description"}
      %label{:for => "checkbox1"}
        %input#checkbox1{:style => "display: none;", :type => "checkbox"}
        %span.custom.checkbox
        Multiple Answers
      %input{:type => "text", :placeholder=>"Option 1"}
      .addHere
        .addButton
          %input{:type => "text", :placeholder=>"Option 2"}
          .clearfix
            %a.small.button.success.right.addMore{:href => "#"} +
      -# .addButton.newAdded
      -#   %input{:type => "text", :placeholder=>"Option 3"}
      -#   %div.clearfix
      -#     %button.small.button.alert.right{:title => "Remove This"}
      -#       &dash;
      -#     %button.small.button.success.right{:title => "Add More"}
      -#       +
      %input.button.round{:type => "submit", :value => "Submit"} 

    %form.custom.askForVotes#tabCont_2.tabDetails{:action => ""} 
      %input{:type => "text", :placeholder=>"Topic"}
      %textarea{:name => "", :cols => "30", :rows => "10", :placeholder => "Description"}
      .addButton
        %textarea{:name => "", :cols => "30", :rows => "10", :placeholder => "Add Suggestion"}
        %div
          %button.small.button.success.right{:title => "Add More"}
            +
      .addButton.newAdded
        %textarea{:name => "", :cols => "30", :rows => "10", :placeholder => "Add Suggestion"}
        .clearfix
          %button.small.button.alert.right{:title => "Remove This"}
            &dash;
          %button.small.button.success.right{:title => "Add More"}
            +
      %input.button.round{:type => "submit", :value => "Submit"} 
  

app/views/pages/blah.html.haml
Blah blah

app/views/pages/index.html.haml
%h1
  Welcome to WhatSay?
%h4
  The act of smelling something, anything, is remarkably like the act of thinking. Immediately at the moment of perception, you can feel the mind going to work, sending the odor around from place to place, setting off complex repertories through the brain, polling one center after another for signs of re recognition, for old memories and old connection
.row
  .large-6.columns
    %h5
      %a{:href => "#"}
        Login
    .login-form
      = form_for(resource, :as => resource_name, :url => session_path(resource_name), :validate => true, :html => { :id => "login_form" }) do |f|
        %label.control-label{:for => "user_email"}
        = f.email_field :email, :placeholder => "Email"
        %label.control-label{:for => "user_password"}
        = f.password_field :password, :placeholder => "Password"
        = f.submit "Login", :class => "button"

  .large-6.columns
    %h5
      %a{:href => "#"}
        Register
    .signup-form
      = form_for(resource, :as => resource_name, :url => registration_path(resource_name), :validate => true) do |f|
        = f.text_field :first_name, :placeholder => "First Name"
        = f.text_field :last_name, :placeholder => "Last Name"
        = f.email_field :email, :placeholder => "Email"
        = f.password_field :password, :placeholder => "Password"
        = f.password_field :password_confirmation, :placeholder => "Confirm Password"
        = f.submit "Sign Up", :class => "button"

:javascript
  $(document).ready(function(){
    $('#login_form').validate({
      rules: {
        user_email: {
          required: true,
          email: true
        },
        user_password: "required"
      }
    });

    $('#new_user').validate({
      rules: {
        user_first_name: {
          require: true,
          minLength: 2,
          maxLength: 20
        },
        user_last_name: {
          require: true,
          maxLength: 20
        },
        user_email: {
          required: true,
          email: true
        },
        user_password: "required",
        user_password_confirmation: "required"
      }
    });
  });

app/views/pages/show_poll.html.haml
.row
  .box.large-8.large-offset-2
  	%h1
      Topic
    %p Description blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah vv
    

app/views/pages/suggestions.html.haml
.pollBox
  %h3 Title Of The Suggestion
  %label
    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer
    took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essentially unchanged.
    It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
    and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
  .result
    %table
      %tbody
        %tr
          %th Idea
          %th Description
          %th Givers
        %tr
          %td
            %label Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus.
          %td
            %label Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et, bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum.
          %td
            %label user webonise
        %tr
          %td
            %label Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus.
          %td
            %label Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et, bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum.
          %td
            %label user webonise
        %tr
          %td
            %label Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus.
          %td
            %label Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et, bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum.
          %td
            %label user webonise
        %tr
          %td
            %label Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus.
          %td
            %label Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et, bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum.
          %td
            %label user webonise

app/views/pages/the_poll.html.haml
.pollBox
  %h3 Title of the poll
  %label
    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer
    took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essentially unchanged.
    It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
    and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
  .result
    %ul.large-12
      %li.large-3.blueFont Yes
      %li.large-9 60%
      %li.large-3.blueFont No
      %li.large-9 40%
      %li.large-3.blueFont May-Be
      %li.large-9 79%
      %li.large-3.blueFont Optional
      %li.large-9 12%

app/views/polls/index.html.haml
.row
  .box.large-10.large-offset-1
    %ul.tabs.switchForm
      %li.large-4.columns.selected
        %a{:href => ""} My Polls
      %li.large-4.columns
        %a{:href => ""} Top Polls
      %li.large-4.columns
        %a{:href => ""} Current Polls
    .topPolls.tabDetails#tabCont_1
      %h5 My Polls
      %a.createNew{:href => "/polls/new"} 
        Create a new poll
      %ul
        - @my_polls.each do |my_poll|
          %li
            %a.pollQuestion{:href => "/polls/#{my_poll.id}"} #{my_poll.topic}
            -#%span.pollQuestion Top Polling Question
            - my_poll.field_options.each do |poll_option| 
              %strong #{poll_option}
              %strong #{my_poll.answers.where(:choice=>poll_option).to_a.size}
            %ul.stars
              %li
                %a{:href => "#"} 
              %li
                %a{:href => "#"} 
              %li
                %a{:href => "#"} 
              %li
                %a{:href => "#"} 
              %li
                %a{:href => "#"} 
    .topPolls.tabDetails#tabCont_2
      %h5 top polls
      %ul
        - @top_polls.each do |top_poll|
          %li
            %a.pollQuestion{:href => "/polls/#{top_poll.id}"} #{top_poll.topic}
            -#%span.pollQuestion Top Polling Question
            - top_poll.field_options.each do |poll_option| 
              %strong #{poll_option}
              %strong #{top_poll.answers.where(:choice=>poll_option).to_a.size}            
            %ul.stars
              %li
                %a{:href => "#"} 
              %li
                %a{:href => "#"} 
              %li
                %a{:href => "#"} 
              %li
                %a{:href => "#"} 
              %li
                %a{:href => "#"}
    .currentPolls.tabDetails#tabCont_3
      %h5 Current polls
      %ul
        - @latest_polls.each do |latest_poll|
          %li
            %a.pollQuestion{:href => "/polls/#{latest_poll.id}"} #{latest_poll.topic}
            -#%span.pollQuestion Top Polling Question            
            - latest_poll.field_options.each do |poll_option| 
              %strong #{poll_option}
              %strong #{latest_poll.answers.where(:choice=>poll_option).to_a.size} 
            %ul.stars
              %li
                %a{:href => "#"} 
              %li
                %a{:href => "#"} 
              %li
                %a{:href => "#"} 
              %li
                %a{:href => "#"} 
              %li
                %a{:href => "#"} 

app/views/polls/new.html.haml
.row
  .large-8.large-offset-2
    %ul.no-bullet.switchForm
      %li.large-6
        %a{:href => "#"} Ask for Votes
      -#%li.large-6
      -#  %a{:href => "#"} Ask for Suggestions
.row
  .large-8.large-offset-2
    = form_for(@poll, :url => polls_path(@poll),:html => {:class => "custom",:id => "tabCont_1"} ) do |f|
      = f.hidden_field :type, :value => "Vote"
      = f.text_field :topic, :placeholder=>"Topic"
      = f.text_area :description, :cols => "30", :rows => "10", :placeholder => "Description"
      -#%textarea{:name => "", :cols => "30", :rows => "10", :placeholder => "Description"}
      %label{:for => "checkbox1"}
        Multiple Answers
        = f.check_box :multiple_ans, :checked => false
      -#%input{:type => "text", :placeholder=>"Option 1"}
      = f.fields_for :field_options do |options|
        = options.text_field :option1,:placeholder=>"Enter option text here"
        .optionFields
          .addButton
            %input{:type => "text", :name => "poll[field_options][option2]", :placeholder=>"Enter option text here"}
            %div
              %button.small.button.success.right.addMoreButton{:type => "button", :title => "Add More"}
                +
          -#.addButton.newAdded
          -#  %input{:type => "text", :placeholder=>"Option 3"}
          -#  %div
          -#    %button.small.button.alert.right{:title => "Remove This"}
          -#      &dash;
          -#   %button.small.button.success.right{:title => "Add More"}
          -#      +
      %input.button.votePollSubmit.round{:type => "submit", :value => "Submit"}

    %form.custom.askForVotes#tabCont_2.tabDetails{:action => ""}
      %input{:type => "text", :placeholder=>"Topic"}
      %textarea{:name => "", :cols => "30", :rows => "10", :placeholder => "Description"}
      .addButton
        %textarea{:name => "", :cols => "30", :rows => "10", :placeholder => "Add Suggestion"}
        %div
          %button.small.button.success.right{:type => "button", :title => "Add More"}
            +
      .addButton.newAdded
        %textarea{:name => "", :cols => "30", :rows => "10", :placeholder => "Add Suggestion"}
        %div
          %button.small.button.alert.right{:type => "button", :title => "Remove This"}
            &dash;
          %button.small.button.success.right{:type => "button", :title => "Add More"}
            +

:javascript
  $(document).ready(function(){

    var optionFieldsDiv = $('.optionFields');
    $(document).on('click', '.optionFields .addMoreButton', function(e) {
      var i = $('.optionFields input[type=text]').size()+1;
      e.preventDefault();
      $('<div class="addButton newAdded"><input type="text" name="poll[field_options][option'+ (i+1) +']" placeholder="Enter option text here"}<div><button class="small button alert right removeButton" title="Remove This" type="button">&dash;</button><button class="small button success right addMoreButton" title="Add More" type="button">+</button></div></div>').appendTo(optionFieldsDiv);
      // remove previous options' add/remove buttons
      $(this).siblings('.removeButton').remove();
      $(this).remove(); // removes current clicked addMoreButton
      i++;
      return false;
    }).on('click', '.removeButton', function(e) {
      var i = $('.optionFields input[type=text]').size() + 1;
      e.preventDefault();
      console.log(i);
      if(i > 2) {
        $(this).parent('.addButton').prev('.newAdded').append('<input name="poll[field_options][option'+ (i+1) +']" type="text" placeholder="Enter option text here"}<div><button class="small button alert right removeButton" title="Remove This" type="button">&dash;</button><button class="small button success right addMoreButton" title="Add More" type="button">+</button>');
        i--;
        $(this).parents('.newAdded').remove();
      }
      else if(i == 2) {
        $(this).parent('.addButton').prev('.addButton').append('<input type="text" placeholder="Enter option text here"}<div><button class="small button success right addMoreButton" title="Add More" type="button">+</button>');
      }
      return false;
    })
  });

app/views/polls/show.html.haml
%row
  .box.large.large-offset-2
    = form_for(@poll, :url => poll_path(@poll),:html => {:class => "custom",:id => "tabCont_1", :method => :put} ) do |f|
      %h2
        #{@poll.topic}
      %p
        %strong Description:
        #{@poll.description}
      - @poll.field_options.each_with_index do |option,index|
        %label{:for => ""}
          - unless @poll.multiple_ans
            = radio_button_tag(:answers, option)
            #{option}
          - else
            = check_box("answers","#{index}",{},"#{option}", 0)
            #{option}

      = f.submit "Vote!", class: "button"